[phases.setup]
nixPkgs = ["python39", "pip"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "cd services/fastapi && python -m uvicorn app-production:app --host 0.0.0.0 --port $PORT"
