# Railway configuration for native Python deployment - Updated
[deploy]
startCommand = "uvicorn api_backend:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
