# Railway configuration for native Python deployment
[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python run.py"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PYTHON_VERSION = "3.11"
PORT = "8000"
